# router WGPay selector file
# format: tunnel_ip dscp_class comment
# STEP_035B: one proven canary only, no production-wide switch
10.253.1.10 cs5 canary_vpn2

# STEP_037B: second canary for cs2 -> vpn4
10.253.1.11 cs2 canary_vpn4
10.253.1.12 cs3 canary_vpn5
10.253.1.13 cs4 canary_vpn1
10.253.1.14 cs1 canary_vpn3
