#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG="/usr/local/sbin/router-wgpay-egress-local-loop.sh"

start_service() {
  procd_open_instance
  procd_set_param command "$PROG"
  procd_set_param respawn 3600 5 5
  procd_set_param stdout 0
  procd_set_param stderr 0
  procd_close_instance
}

stop_service() {
  return 0
}
